# Generated by Django 4.2.3 on 2023-08-30 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_reserva_petshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='petshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='base.petshop'),
        ),
    ]
