# Generated by Django 4.2.3 on 2023-09-25 19:12

from django.db import migrations

# from base.models import Reserva, Petshop


def atualizar_petshop_reserva(apps, schema_editor):
    Reserva = apps.get_model('base', 'Reserva')
    Petshop = apps.get_model('base', 'Petshop')
    petshop = Petshop.objects.create(nome='Padrão', telefone='Padrão', endereco='Padrão')
    for reserva in Reserva.objects.filter(petshop__isnull=True):
        reserva.petshop = petshop
        reserva.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_petshop_telefone_alter_reserva_nome_pet_and_more'),
    ]

    operations = [
        migrations.RunPython(atualizar_petshop_reserva)
    ]
