# Generated by Django 4.2.3 on 2023-09-25 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={},
        ),
    ]
